/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AerospaceDefenceSoftwareRouteImport } from './routes/aerospace-defence-software'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ProfessionalProfileRouteImport } from './routes/professional-profile'
import { Route as ResumeRouteImport } from './routes/resume'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AerospaceDefenceSoftwareRoute =
  AerospaceDefenceSoftwareRouteImport.update({
    id: '/aerospace-defence-software',
    path: '/aerospace-defence-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalProfileRoute = ProfessionalProfileRouteImport.update({
  id: '/professional-profile',
  path: '/professional-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aerospace-defence-software': typeof AerospaceDefenceSoftwareRoute
  '/career': typeof CareerRoute
  '/professional-profile': typeof ProfessionalProfileRoute
  '/resume': typeof ResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aerospace-defence-software': typeof AerospaceDefenceSoftwareRoute
  '/career': typeof CareerRoute
  '/professional-profile': typeof ProfessionalProfileRoute
  '/resume': typeof ResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aerospace-defence-software': typeof AerospaceDefenceSoftwareRoute
  '/career': typeof CareerRoute
  '/professional-profile': typeof ProfessionalProfileRoute
  '/resume': typeof ResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aerospace-defence-software'
    | '/career'
    | '/professional-profile'
    | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aerospace-defence-software'
    | '/career'
    | '/professional-profile'
    | '/resume'
  id:
    | '__root__'
    | '/'
    | '/aerospace-defence-software'
    | '/career'
    | '/professional-profile'
    | '/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AerospaceDefenceSoftwareRoute: typeof AerospaceDefenceSoftwareRoute
  CareerRoute: typeof CareerRoute
  ProfessionalProfileRoute: typeof ProfessionalProfileRoute
  ResumeRoute: typeof ResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aerospace-defence-software': {
      id: '/aerospace-defence-software'
      path: '/aerospace-defence-software'
      fullPath: '/aerospace-defence-software'
      preLoaderRoute: typeof AerospaceDefenceSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional-profile': {
      id: '/professional-profile'
      path: '/professional-profile'
      fullPath: '/professional-profile'
      preLoaderRoute: typeof ProfessionalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AerospaceDefenceSoftwareRoute: AerospaceDefenceSoftwareRoute,
  CareerRoute: CareerRoute,
  ProfessionalProfileRoute: ProfessionalProfileRoute,
  ResumeRoute: ResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
